apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-test
  namespace: postgres-test
spec:
  instances: 1
  postgresql:
    parameters:
      max_connections: "100"
  storage:
    size: 1Gi
  managed:
    roles:
      - name: myapp
        ensure: present
        login: true
        passwordSecret:
          name: myapp-credentials
