apiVersion: v1
kind: Pod
metadata:
  name: myapp-psql-test
  namespace: myapp
spec:
  restartPolicy: Never
  containers:
    - name: psql
      image: postgres:18
      command:
        - psql
        - postgresql://$(DB_USER):$(DB_PASSWORD)@postgres-test-rw.postgres-test.svc.cluster.local:5432/myapp
        - -c
        - "SELECT current_user, current_database(), inet_server_addr();"
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: myapp-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-credentials
              key: password
