#cloud-config
runcmd:
  - |
    IP=$(hostname -I | awk '{print $1}')
    curl -sfL https://get.k3s.io \
      | K3S_TOKEN='${K3S_TOKEN}' \
        INSTALL_K3S_EXEC="server --tls-san k3s-cp.orb.local --tls-san ${IP} --advertise-address=${IP} --node-ip=${IP}" \
        sh -s -
