apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  postgresql:
    parameters:
      max_connections: "100"
  storage:
    size: 10Gi
  affinity:
    podAntiAffinityType: required
  managed:
    roles:
      - name: someapp
        login: true
        passwordSecret:
          name: someapp-credentials
